import type { FeaturedEvent } from "./featuredEvents.types";

export const featuredEventsData: FeaturedEvent[] = [
  {
    id: 1,
    title: "JUSTIN BIEBER LIVE",
    category: "SYNTH RESONANCE & VISUALS",
    tagline: "High-voltage synth wave & visual overdrive",
    description: "Multi-stage kinetic audio-visual spectacle featuring international synth and techno visionaries in a laser-bathed amphitheatre.",
    date: "OCT 24",
    fullDate: "October 24-26, 2026",
    time: "20:00 - 05:00",
    venue: "Echo Arena Main Hall",
    location: "Guwahati, Assam",
    price: "₹899",
    image: "/images/events/event19.webp",
    status: "selling_fast",
    lineup: ["Tale of Us", "Amelie Lens", "Boris Brejcha", "Rebūke", "ANNA"],
  },
  {
    id: 2,
    title: "CREATIVE EVENINGS",
    category: "FRIENDS & NETWORKING",
    tagline: "A curated evening of networking, collaboration, and creative exchange.",
    description: "Join fellow creatives for an intimate gathering featuring live performances, interactive installations, and collaborative workshops designed to spark inspiration and foster meaningful connections.",
    date: "NOV 12",
    fullDate: "November 12-14, 2026",
    time: "18:00 - 04:00",
    venue: "Skyline Underground",
    location: "Shillong, Meghalaya",
    price: "₹1,199",
    image: "/images/events/event11.webp",
    status: "live",
    lineup: ["Carl Cox", "Solomun", "Charlotte de Witte", "Mind Against", "KAS:ST"],
  },
  {
    id: 3,
    title: "ECHO FESTIVAL",
    category: "OPEN AIR ARENA & FOOD",
    tagline: "Three days of transcendent sound, art & community",
    description: "Open-air gathering featuring modular analog synthesizers, organic food villages, and panoramic sunset stages overlooking the valley.",
    date: "NOV 28",
    fullDate: "November 28-30, 2026",
    time: "14:00 - 02:00",
    venue: "Tea Garden Amphitheatre",
    location: "Jorhat, Assam",
    price: "₹1,499",
    image: "/images/events/event3.webp",
    status: "selling_fast",
    lineup: ["Richie Hawtin", "Dax J", "Paula Temple", "I Hate Models", "Kobosil"],
  },
  {
    id: 4,
    title: "TED TALKS LIVE",
    category: "INNOVATION & IDEAS",
    tagline: "A live TED Talk experience featuring thought leaders and innovators from around the world.",
    description: "Engage with visionary speakers, participate in interactive Q&A sessions, and explore cutting-edge ideas that are shaping the future of technology, culture, and society.",
    date: "DEC 05",
    fullDate: "December 05, 2026",
    time: "21:30 - 04:30",
    venue: "Pulse Warehouse",
    location: "Dibrugarh, Assam",
    price: "₹999",
    image: "/images/events/event21.webp",
    status: "upcoming",
    lineup: ["Max Richter", "Nils Frahm", "Kiasmos", "Ólafur Arnalds", "Jon Hopkins"],
  },
  {
    id: 5,
    title: "SOUND / SPACE",
    category: "SPATIAL AUDIO & IMMERSIVE",
    tagline: "Generative holographic light & acoustic alchemy",
    description: "High-frequency breakbeats, seismic subwoofers, and neon reactive projection mapping inside a consecrated cultural space.",
    date: "DEC 18",
    fullDate: "December 18, 2026",
    time: "19:00 - 01:00",
    venue: "Pragjyoti Cultural Center",
    location: "Guwahati, Assam",
    price: "₹1,299",
    image: "/images/events/event18.webp",
    status: "selling_fast",
    lineup: ["Noisia", "Pendulum", "Chase & Status", "Sub Focus", "Camo & Krooked"],
  },

    {
    id: 6,
    title: "FLIM SESSION",
    category: "CINEMATIC & VISUAL ARTS",
    tagline: "A curated evening of cinematic experiences, live scoring, and visual storytelling.",
    description: "Experience a fusion of film, music, and visual arts with live scoring performances, immersive screenings, and interactive discussions with filmmakers and composers.",
    date: "DEC 18",
    fullDate: "December 18, 2026",
    time: "19:00 - 01:00",
    venue: "Pragjyoti Cultural Center",
    location: "Guwahati, Assam",
    price: "₹1,299",
    image: "/images/events/event23.webp",
    status: "selling_fast",
    lineup: ["Noisia", "Pendulum", "Chase & Status", "Sub Focus", "Camo & Krooked"],
  },
];
