import type { GalleryItem } from "./gallery.types";

export const galleryRowsData: GalleryItem[][] = [
  // Stream 1 (Moves Left)
  [
    {
      id: "g-01",
      title: "CYBERIA TAKEOVER",
      category: "SYNTH RESONANCE",
      location: "Guwahati",
      date: "OCT 2025",
      attendees: "2,400+",
      image: "/images/events/event13.webp",
    },
    {
      id: "g-02",
      title: "SOLARIS NOCTURNE",
      category: "ROOFTOP SESSION",
      location: "Shillong",
      date: "NOV 2025",
      attendees: "1,200+",
      image: "/images/events/event14.webp",
    },
    {
      id: "g-03",
      title: "SUBTERRA WAREHOUSE",
      category: "UNDERGROUND TECHNO",
      location: "Jorhat",
      date: "DEC 2025",
      attendees: "1,800+",
      image: "/images/events/event15.webp",
    },
    {
      id: "g-04",
      title: "AURORA OPEN AIR",
      category: "AMPHITHEATRE LIVE",
      location: "Guwahati",
      date: "JAN 2026",
      attendees: "3,500+",
      image: "/images/events/event16.webp",
    },
  ],
  // Stream 2 (Moves Right - Fast)
  [
    {
      id: "g-05",
      title: "PULSE MATRIX",
      category: "LASER AUDIO-VISUAL",
      location: "Dibrugarh",
      date: "FEB 2026",
      attendees: "1,600+",
      image: "/images/events/event17.webp",
    },
    {
      id: "g-06",
      title: "PRISM HORIZON",
      category: "SUNSET FREQUENCY",
      location: "Guwahati",
      date: "MAR 2026",
      attendees: "2,100+",
      image: "/images/events/event18.webp",
    },
    {
      id: "g-07",
      title: "ECHO SYMPHONY",
      category: "ORCHESTRAL HYBRID",
      location: "Shillong",
      date: "APR 2026",
      attendees: "2,800+",
      image: "/images/events/event19.webp",
    },
    {
      id: "g-08",
      title: "NEBULA GROOVES",
      category: "DEEP MEZZANINE",
      location: "Jorhat",
      date: "MAY 2026",
      attendees: "1,400+",
      image: "/images/events/event20.webp",
    },
  ],
  // Stream 3 (Moves Left - Ambient)
  [
    {
      id: "g-09",
      title: "AFTER HOURS REVEAL",
      category: "SECRET STAGE",
      location: "Guwahati",
      date: "JUN 2026",
      attendees: "900 VIPs",
      image: "/images/events/event21.webp",
    },
    {
      id: "g-10",
      title: "TRANSCENDENCE",
      category: "IMMERSIVE DOME",
      location: "Shillong",
      date: "JUL 2026",
      attendees: "3,100+",
      image: "/images/events/event22.webp",
    },
    {
      id: "g-11",
      title: "MIDNIGHT PROTOCOL",
      category: "BASS EXPERIMENT",
      location: "Dibrugarh",
      date: "AUG 2026",
      attendees: "1,500+",
      image: "/images/events/event23.webp",
    },
    {
      id: "g-12",
      title: "APEX FINALE",
      category: "ANNUAL ARENA",
      location: "Guwahati",
      date: "AUG 2026",
      attendees: "5,000+",
      image: "/images/events/event24.webp",
    },
  ],
];
