import type { HeroEvent } from "./hero.types";

export const heroEventsData: HeroEvent[] = [
  {
    id: 1,
    title: "Metallica De Tour",
    category: "FESTIVAL & RAVE",
    tagline: "A monumental 3-night odyssey through futuristic sound architecture and kinetic lasers.",
    description: "Immerse yourself in neon-drenched kinetic stages, cutting-edge spatial audio, and transcendent performances from global electronic visionaries.",
    date: "OCT 24",
    fullDate: "October 24, 2026",
    time: "20:00 - 05:00",
    venue: "Cyber Dome Pavilion",
    location: "Dibrughar, Assam",
    city: "Dibrughar, Assam",
    price: "₹899",
    image: "/images/hero/hero5.webp",
    label: "LIVE SHOWCASE",
    soundPreviewName: "HYPERDRIVE LIVE MIX",
  },
  {
    id: 2,
    title: "Arjit Singh Live",
    category: "OPEN AIR FESTIVAL",
    tagline: "Where ancient rhythms collide with cutting-edge open-air techno euphoria.",
    description: "Feel the earth shake beneath monolithic lasers as the world's most relentless selectors take you past the horizon of sound.",
    date: "NOV 12",
    fullDate: "November 12, 2026",
    time: "18:00 - 04:00",
    venue: "Helios Amphitheater",
    location: "Goa",
    city: "Goa, IN",
    price: "₹1,199",
    image: "/images/hero/hero4.webp",
    label: "SELLING FAST",
    soundPreviewName: "SOLAR TECHNO TRIP",
  },
  {
    id: 3,
    title: "CYBERPUNK WAREHOUSE",
    category: "TECHNO & INDUSTRIAL",
    tagline: "Industrial subterranean rave engineered for raw analog sonic pressure.",
    description: "Raw subterranean pressure, analog modular synthesizers, and strobe-bathed darkness inside an abandoned subterranean foundry.",
    date: "NOV 28",
    fullDate: "November 28, 2026",
    time: "22:00 - 06:00",
    venue: "Vault 09 Foundry",
    location: "Berlin",
    city: "Berlin, DE",
    price: "₹1,499",
    image: "/images/events/event7.webp",
    label: "EXCLUSIVE PASS",
    soundPreviewName: "ACID UNDERGROUND BEAT",
  },
  {
    id: 4,
    title: "Color Cosmos",
    category: "AMBIENT & EXPERIMENTAL",
    tagline: "Transcendental spatial audio journey under a kinetic star-lit dome ceiling.",
    description: "A meditative yet profound multi-sensory symphony uniting modular ambient synthesis with live orchestral harmonics.",
    date: "DEC 05",
    fullDate: "December 05, 2026",
    time: "19:30 - 23:30",
    venue: "Aurora Cathedral",
    location: "Reykjavik",
    city: "Reykjavik, IS",
    price: "₹999",
    image: "/images/events/event8.webp",
    label: "LIMITED SEATS",
    soundPreviewName: "ASTRAL DRONE STREAM",
  },
  {
    id: 5,
    title: "ProductCON X",
    category: "BUSINESS & TECHNOLOGY",
    tagline: "Hyper-speed breakbeats, seismic subwoofers and holographic laser matrices.",
    description: "High-frequency breakbeats, seismic subwoofers, and neon reactive holographic projection mapping in a converted aircraft hangar.",
    date: "DEC 18",
    fullDate: "December 18, 2026",
    time: "21:00 - 05:00",
    venue: "Hangar 44 Airbase",
    location: "London",
    city: "London, UK",
    price: "₹1,299",
    image: "/images/events/event9.webp",
    label: "NEW RELEASE",
    soundPreviewName: "QUANTUM BASS PULSE",
  },
];
