import type { TelemetryMetricEntity, PromoDiscountEntity } from "../../server/db/schema";
import type { EventInventoryStatus } from "./admin.types";

export const initialAdminMetrics: TelemetryMetricEntity = {
  totalRevenue: 3489200,
  totalTicketsSold: 3840,
  totalTicketsRemaining: 1160,
  totalEventsActive: 6,
  liveVisitorsNow: 142,
  dailyConversionRate: 4.8,
  salesVelocityPerHour: 38,
  revenueByTier: {
    GA: 1720000,
    VIP: 1185000,
    BACKSTAGE: 584200,
  },
};

export const initialPromoCodes: PromoDiscountEntity[] = [
  {
    id: "p-01",
    code: "ECHOFIRST20",
    discountPercentage: 20,
    maxDiscountAmount: 300,
    applicableTiers: ["GA", "VIP"],
    expiresAt: "2026-10-31",
    usageCount: 142,
    usageLimit: 500,
    isActive: true,
  },
  {
    id: "p-02",
    code: "VIPGUESTLIST",
    discountPercentage: 25,
    maxDiscountAmount: 600,
    applicableTiers: ["VIP", "BACKSTAGE"],
    expiresAt: "2026-11-30",
    usageCount: 88,
    usageLimit: 150,
    isActive: true,
  },
  {
    id: "p-03",
    code: "FLASHSALE10",
    discountPercentage: 10,
    maxDiscountAmount: 150,
    applicableTiers: ["GA"],
    expiresAt: "2026-09-15",
    usageCount: 412,
    usageLimit: 1000,
    isActive: true,
  },
];

export const initialInventoryStock: EventInventoryStatus[] = [
  {
    eventId: "upcoming-01",
    eventTitle: "After Dark",
    category: "Late Night Electronic",
    eventDate: "24 AUG 2026",
    venue: "Skyline Underground, Guwahati",
    totalCapacity: 1200,
    totalSold: 980,
    totalRemaining: 220,
    totalRevenue: 842600,
    tiers: [
      {
        tierName: "GA",
        totalCapacity: 800,
        ticketsSold: 710,
        ticketsRemaining: 90,
        price: 499,
        revenueGenerated: 354290,
      },
      {
        tierName: "VIP",
        totalCapacity: 300,
        ticketsSold: 210,
        ticketsRemaining: 90,
        price: 1199,
        revenueGenerated: 251790,
      },
      {
        tierName: "BACKSTAGE",
        totalCapacity: 100,
        ticketsSold: 60,
        ticketsRemaining: 40,
        price: 2499,
        revenueGenerated: 149940,
      },
    ],
  },
  {
    eventId: "upcoming-02",
    eventTitle: "Echo Nights",
    category: "Live Concert & Audio-Visual",
    eventDate: "28 AUG 2026",
    venue: "Historic Ruins Pavilion, Sivasagar",
    totalCapacity: 1500,
    totalSold: 1240,
    totalRemaining: 260,
    totalRevenue: 792400,
    tiers: [
      {
        tierName: "GA",
        totalCapacity: 1000,
        ticketsSold: 890,
        ticketsRemaining: 110,
        price: 399,
        revenueGenerated: 355110,
      },
      {
        tierName: "VIP",
        totalCapacity: 350,
        ticketsSold: 260,
        ticketsRemaining: 90,
        price: 899,
        revenueGenerated: 233740,
      },
      {
        tierName: "BACKSTAGE",
        totalCapacity: 150,
        ticketsSold: 90,
        ticketsRemaining: 60,
        price: 1799,
        revenueGenerated: 161910,
      },
    ],
  },
  {
    eventId: "upcoming-03",
    eventTitle: "Midnight Sessions",
    category: "Intimate Studio Sessions",
    eventDate: "02 SEP 2026",
    venue: "The Velvet Loft, Jorhat",
    totalCapacity: 600,
    totalSold: 460,
    totalRemaining: 140,
    totalRevenue: 524000,
    tiers: [
      {
        tierName: "GA",
        totalCapacity: 400,
        ticketsSold: 320,
        ticketsRemaining: 80,
        price: 599,
        revenueGenerated: 191680,
      },
      {
        tierName: "VIP",
        totalCapacity: 150,
        ticketsSold: 110,
        ticketsRemaining: 40,
        price: 1299,
        revenueGenerated: 142890,
      },
      {
        tierName: "BACKSTAGE",
        totalCapacity: 50,
        ticketsSold: 30,
        ticketsRemaining: 20,
        price: 2199,
        revenueGenerated: 65970,
      },
    ],
  },
  {
    eventId: "upcoming-04",
    eventTitle: "Afterglow",
    category: "Sunset to Starlight Experience",
    eventDate: "08 SEP 2026",
    venue: "Riverview Tiered Gardens, Guwahati",
    totalCapacity: 900,
    totalSold: 620,
    totalRemaining: 280,
    totalRevenue: 684000,
    tiers: [
      {
        tierName: "GA",
        totalCapacity: 600,
        ticketsSold: 430,
        ticketsRemaining: 170,
        price: 699,
        revenueGenerated: 300570,
      },
      {
        tierName: "VIP",
        totalCapacity: 220,
        ticketsSold: 150,
        ticketsRemaining: 70,
        price: 1399,
        revenueGenerated: 209850,
      },
      {
        tierName: "BACKSTAGE",
        totalCapacity: 80,
        ticketsSold: 40,
        ticketsRemaining: 40,
        price: 3499,
        revenueGenerated: 139960,
      },
    ],
  },
  {
    eventId: "upcoming-05",
    eventTitle: "Frequency",
    category: "Audiophile Club Night",
    eventDate: "14 SEP 2026",
    venue: "Bass Vault 01, Guwahati",
    totalCapacity: 800,
    totalSold: 540,
    totalRemaining: 260,
    totalRevenue: 646200,
    tiers: [
      {
        tierName: "GA",
        totalCapacity: 500,
        ticketsSold: 360,
        ticketsRemaining: 140,
        price: 799,
        revenueGenerated: 287640,
      },
      {
        tierName: "VIP",
        totalCapacity: 200,
        ticketsSold: 130,
        ticketsRemaining: 70,
        price: 1599,
        revenueGenerated: 207870,
      },
      {
        tierName: "BACKSTAGE",
        totalCapacity: 100,
        ticketsSold: 50,
        ticketsRemaining: 50,
        price: 2899,
        revenueGenerated: 144950,
      },
    ],
  },
];
