import type { SearchableEvent, SearchCategoryTab, SearchLocationTab, GlobalLocationItem } from "./search.types";
import { assetUrl } from "../../utils/assetHelper";

export const searchRotatingPlaceholders: string[] = [
  "Search events, artists, venues...",
  "Search 'Metallica De Tour'...",
  "Search 'Neon Nights'...",
  "Search 'Guwahati'...",
  "Search 'Justin Bieber Live'...",
  "Search 'Shillong'...",
  "Search 'Arjit Singh Live'...",
  "Search 'Tuileries Festival'...",
  "Search 'Open Air Festivals'...",
  "Search 'Cyberpunk Warehouse'...",
  "Search 'Jorhat'...",
  "Search 'TED Talks Live'...",
];

export const searchCategoryTabs: SearchCategoryTab[] = [
  { id: "ALL", label: "All Categories", genre: "ALL" },
  { id: "MUSIC", label: "Live Music & Synth", genre: "MUSIC" },
  { id: "FESTIVAL", label: "Open Air & Festivals", genre: "FESTIVAL" },
  { id: "NIGHTLIFE", label: "Clubs & After Hours", genre: "NIGHTLIFE" },
  { id: "TALKS", label: "Tech & Innovation", genre: "TALKS" },
  { id: "ARTS", label: "Cinema & Visual Arts", genre: "ARTS" },
];

export const searchLocationTabs: SearchLocationTab[] = [
  { id: "ALL", city: "All Locations" },
  { id: "Guwahati", city: "Guwahati" },
  { id: "Shillong", city: "Shillong" },
  { id: "Jorhat", city: "Jorhat" },
  { id: "Dibrugarh", city: "Dibrugarh" },
  { id: "Sivasagar", city: "Sivasagar" },
  { id: "Goa", city: "Goa" },
  { id: "Berlin", city: "Berlin" },
  { id: "Paris", city: "Paris" },
  { id: "London", city: "London" },
  { id: "Reykjavik", city: "Reykjavik" },
];

export const globalLocationsList: GlobalLocationItem[] = [
  { id: "ALL", name: "All Worldwide Locations", region: "Global", country: "Earth", flag: "🌐", eventCount: 14 },
  { id: "Guwahati", name: "Guwahati", region: "Assam", country: "India", flag: "🇮🇳", eventCount: 5 },
  { id: "Shillong", name: "Shillong", region: "Meghalaya", country: "India", flag: "🇮🇳", eventCount: 2 },
  { id: "Jorhat", name: "Jorhat", region: "Assam", country: "India", flag: "🇮🇳", eventCount: 2 },
  { id: "Dibrugarh", name: "Dibrugarh", region: "Assam", country: "India", flag: "🇮🇳", eventCount: 2 },
  { id: "Sivasagar", name: "Sivasagar", region: "Assam", country: "India", flag: "🇮🇳", eventCount: 1 },
  { id: "Goa", name: "Goa", region: "Western Coast", country: "India", flag: "🇮🇳", eventCount: 1 },
  { id: "Berlin", name: "Berlin", region: "Brandenburg", country: "Germany", flag: "🇩🇪", eventCount: 1 },
  { id: "Paris", name: "Paris", region: "Île-de-France", country: "France", flag: "🇫🇷", eventCount: 1 },
  { id: "London", name: "London", region: "Greater London", country: "United Kingdom", flag: "🇬🇧", eventCount: 1 },
  { id: "Reykjavik", name: "Reykjavik", region: "Capital Region", country: "Iceland", flag: "🇮🇸", eventCount: 1 },
  { id: "Mumbai", name: "Mumbai", region: "Maharashtra", country: "India", flag: "🇮🇳", eventCount: 3 },
  { id: "Bengaluru", name: "Bengaluru", region: "Karnataka", country: "India", flag: "🇮🇳", eventCount: 2 },
  { id: "Tokyo", name: "Tokyo", region: "Kanto", country: "Japan", flag: "🇯🇵", eventCount: 2 },
  { id: "Dubai", name: "Dubai", region: "Emirate of Dubai", country: "UAE", flag: "🇦🇪", eventCount: 2 },
  { id: "New York", name: "New York", region: "New York", country: "USA", flag: "🇺🇸", eventCount: 2 },
  { id: "Amsterdam", name: "Amsterdam", region: "North Holland", country: "Netherlands", flag: "🇳🇱", eventCount: 2 },
  { id: "Ibiza", name: "Ibiza", region: "Balearic Islands", country: "Spain", flag: "🇪🇸", eventCount: 1 },
];

export const quickSearchTags: string[] = [
  "Trending Headliners",
  "Guwahati",
  "Shillong",
  "Synth Wave",
  "Open Air",
  "Underground Club",
  "Weekend Passes",
];

export const searchableEventsCatalog: SearchableEvent[] = [
  {
    id: "search-01",
    title: "Metallica De Tour",
    category: "FESTIVAL & RAVE",
    genre: "FESTIVAL",
    date: "24 OCT 2026",
    fullDate: "October 24, 2026",
    time: "20:00 - 05:00",
    venue: "Cyber Dome Pavilion",
    city: "Dibrughar",
    location: "Dibrughar, Assam",
    price: "₹899",
    basePrice: 899,
    image: assetUrl("/images/hero/hero5.webp"),
    tag: "LIVE SHOWCASE",
    description: "A monumental 3-night odyssey through futuristic sound architecture and kinetic lasers.",
    isTrending: true,
    isHeadliner: true,
  },
  {
    id: "search-02",
    title: "JUSTIN BIEBER LIVE",
    category: "SYNTH RESONANCE & VISUALS",
    genre: "MUSIC",
    date: "24 OCT 2026",
    fullDate: "October 24-26, 2026",
    time: "20:00 - 05:00",
    venue: "Echo Arena Main Hall",
    city: "Guwahati",
    location: "Guwahati, Assam",
    price: "₹899",
    basePrice: 899,
    image: assetUrl("/images/events/event19.webp"),
    tag: "HEADLINER",
    description: "Multi-stage kinetic audio-visual spectacle featuring international synth and techno visionaries in a laser-bathed amphitheatre.",
    lineup: ["Tale of Us", "Amelie Lens", "Boris Brejcha", "Rebūke", "ANNA"],
    isTrending: true,
    isHeadliner: true,
  },
  {
    id: "search-03",
    title: "Arjit Singh Live",
    category: "OPEN AIR FESTIVAL",
    genre: "FESTIVAL",
    date: "12 NOV 2026",
    fullDate: "November 12, 2026",
    time: "18:00 - 04:00",
    venue: "Helios Amphitheater",
    city: "Goa",
    location: "Goa, IN",
    price: "₹1,199",
    basePrice: 1199,
    image: assetUrl("/images/hero/hero4.webp"),
    tag: "SELLING FAST",
    description: "Where ancient rhythms collide with cutting-edge open-air techno euphoria.",
    isTrending: true,
    isHeadliner: true,
  },
  {
    id: "search-04",
    title: "CREATIVE EVENINGS",
    category: "FRIENDS & NETWORKING",
    genre: "TALKS",
    date: "12 NOV 2026",
    fullDate: "November 12-14, 2026",
    time: "18:00 - 04:00",
    venue: "Skyline Underground",
    city: "Shillong",
    location: "Shillong, Meghalaya",
    price: "₹1,199",
    basePrice: 1199,
    image: assetUrl("/images/events/event11.webp"),
    tag: "CREATIVE LAB",
    description: "Join fellow creatives for an intimate gathering featuring live performances, interactive installations, and collaborative workshops.",
    lineup: ["Carl Cox", "Solomun", "Charlotte de Witte", "Mind Against"],
    isTrending: true,
  },
  {
    id: "search-05",
    title: "NEON NIGHTS",
    category: "SYNTH WAVE & VISUALS",
    genre: "MUSIC",
    date: "24 AUG 2026",
    fullDate: "Friday, 24 August 2026",
    time: "08:00 PM - 03:00 AM",
    venue: "Echo Arena Main Hall",
    city: "Guwahati",
    location: "Guwahati, Assam",
    price: "₹899",
    basePrice: 899,
    image: assetUrl("/images/events/event15.webp"),
    tag: "POPULAR",
    description: "High-voltage synth wave, laser architecture, and kinetic visuals in the flagship arena.",
    isTrending: true,
  },
  {
    id: "search-06",
    title: "GARBA UNDERGROUND",
    category: "CLUB NIGHT & BASS",
    genre: "NIGHTLIFE",
    date: "31 AUG 2026",
    fullDate: "August 31, 2026",
    time: "10:00 PM - 05:00 AM",
    venue: "Skyline Underground Club",
    city: "Shillong",
    location: "Shillong, Meghalaya",
    price: "₹699",
    basePrice: 699,
    image: assetUrl("/images/events/event2.webp"),
    tag: "UNDERGROUND",
    description: "Late night underground frequencies, strobe tunnels, and visceral low-end bass pressure.",
  },
  {
    id: "search-07",
    title: "ECHO OPEN AIR",
    category: "MULTI-STAGE FESTIVAL",
    genre: "FESTIVAL",
    date: "07 SEP 2026",
    fullDate: "September 07-09, 2026",
    time: "03:00 PM - 02:00 AM",
    venue: "Tea Garden Amphitheatre",
    city: "Jorhat",
    location: "Jorhat, Assam",
    price: "₹1,499",
    basePrice: 1499,
    image: assetUrl("/images/events/event17.webp"),
    tag: "3-DAY PASS",
    description: "Three days of transcendent sound, organic food villages, and valley sunset stages.",
    isTrending: true,
  },
  {
    id: "search-08",
    title: "Tuileries Festival",
    category: "LATE NIGHT TECHNO",
    genre: "NIGHTLIFE",
    date: "24 AUG 2026",
    fullDate: "Saturday, 24 August 2026",
    time: "09:00 PM - 04:00 AM",
    venue: "Skyline Underground",
    city: "Paris",
    location: "Paris, France",
    price: "₹499",
    basePrice: 499,
    image: assetUrl("/images/events/event20.webp"),
    tag: "3D PASS",
    description: "A subterranean odyssey of melodic techno and analog visual synths beneath the cityscape.",
    lineup: ["Kinetix", "Aura Vale", "SubZero DJ"],
  },
  {
    id: "search-09",
    title: "CYBERPUNK WAREHOUSE",
    category: "TECHNO & INDUSTRIAL",
    genre: "NIGHTLIFE",
    date: "28 NOV 2026",
    fullDate: "November 28, 2026",
    time: "22:00 - 06:00",
    venue: "Vault 09 Foundry",
    city: "Berlin",
    location: "Berlin, DE",
    price: "₹1,499",
    basePrice: 1499,
    image: assetUrl("/images/events/event7.webp"),
    tag: "EXCLUSIVE",
    description: "Raw subterranean pressure, modular analog synthesizers, and strobe-bathed darkness.",
    isTrending: true,
  },
  {
    id: "search-10",
    title: "TED TALKS LIVE",
    category: "INNOVATION & IDEAS",
    genre: "TALKS",
    date: "05 DEC 2026",
    fullDate: "December 05, 2026",
    time: "21:30 - 04:30",
    venue: "Pulse Warehouse",
    city: "Dibrugarh",
    location: "Dibrugarh, Assam",
    price: "₹999",
    basePrice: 999,
    image: assetUrl("/images/events/event21.webp"),
    tag: "KEYNOTE & TALKS",
    description: "Engage with visionary speakers, participate in interactive Q&A sessions, and explore cutting-edge ideas.",
  },
  {
    id: "search-11",
    title: "SOUND / SPACE",
    category: "SPATIAL AUDIO & IMMERSIVE",
    genre: "ARTS",
    date: "18 DEC 2026",
    fullDate: "December 18, 2026",
    time: "19:00 - 01:00",
    venue: "Pragjyoti Cultural Center",
    city: "Guwahati",
    location: "Guwahati, Assam",
    price: "₹1,299",
    basePrice: 1299,
    image: assetUrl("/images/events/event18.webp"),
    tag: "IMMERSIVE",
    description: "High-frequency breakbeats, seismic subwoofers, and neon reactive projection mapping inside a consecrated cultural space.",
  },
  {
    id: "search-12",
    title: "FLIM SESSION",
    category: "CINEMATIC & VISUAL ARTS",
    genre: "ARTS",
    date: "18 DEC 2026",
    fullDate: "December 18, 2026",
    time: "19:00 - 01:00",
    venue: "Pragjyoti Cultural Center",
    city: "Guwahati",
    location: "Guwahati, Assam",
    price: "₹1,299",
    basePrice: 1299,
    image: assetUrl("/images/events/event23.webp"),
    tag: "LIVE SCORING",
    description: "Experience a fusion of film, music, and visual arts with live scoring performances, immersive screenings, and discussions.",
  },
  {
    id: "search-13",
    title: "BUSINESS X-TECH SUMMIT",
    category: "INNOVATION & NETWORKING",
    genre: "TALKS",
    date: "28 AUG 2026",
    fullDate: "Wednesday, 28 August 2026",
    time: "07:30 PM - 11:30 PM",
    venue: "Historic Ruins Pavilion",
    city: "Sivasagar",
    location: "Sivasagar, Assam",
    price: "₹399",
    basePrice: 399,
    image: assetUrl("/images/events/event12.webp"),
    tag: "SUMMIT",
    description: "An exclusive evening of networking, keynote talks, and immersive tech showcases for business leaders and innovators.",
  },
  {
    id: "search-14",
    title: "Midnight Sessions",
    category: "INTIMATE STUDIO SESSIONS",
    genre: "MUSIC",
    date: "02 SEP 2026",
    fullDate: "Monday, 02 September 2026",
    time: "09:00 PM - 01:30 AM",
    venue: "The Velvet Loft",
    city: "Jorhat",
    location: "Jorhat, Assam",
    price: "₹599",
    basePrice: 599,
    image: assetUrl("/images/events/event13.webp"),
    tag: "ACOUSTIC",
    description: "Unplugged acoustic tapestries, soul vocals, and intimate late-night storytelling.",
  },
];
